### PR TITLE
Talkback improvements

### PR DESCRIPTION
**Pull request by Merkost**
Added talkback improvements #29

### CODE REVIEW

**Comment by Merkost** [comment]
Almost perfect, but still has some drawbacks, for example, after typing one letter, talkback loses focus

**Comment by Merkost** [comment]
Also I suggest to rename the string string/clipboard_pinned from "Pinned" to "Pinned clipboard" or similar in order to make the talkback text pronunciation more understandable by people

**Comment by Merkost** [comment]
Focus losses on typing letters were fixed, but it still exists when you change layout of your keyboard for example. If that's crucial, I'll investigate further. @tibbi

**Comment by tibbi** [comment]
if you add new strings, add them into all languages please. The languages you cannot speak just use english, do not use any machine translations.

**Comment by tibbi** [comment]
space should be changed to spacebar though to make it clearer

**Comment by tibbi** [comment]
looks good, thanks

**Pull request merged**
