### PR TITLE
Add Polish keyboard layout

### PR DESCRIPTION
**Pull request by starsep**

### CODE REVIEW

**Comment by tibbi** [comment]
you removed many alternative letters, they arent present in Gboard etc either? Also, if you long press "e", lets make "3" selected by default. Same at "o".

**Comment by starsep** [comment]
> you removed many alternative letters, they arent present in Gboard etc either? Also, if you long press "e", lets make "3" selected by default. Same at "o".

They are present in Gboard. I can restore them but I am not sure whether I should. For example [Slovenian](https://github.com/SimpleMobileTools/Simple-Keyboard/blob/main/app/src/main/res/xml/keys_letters_slovenian.xml) doesn't have them.
I used English QWERTY as a base.

Could you explain how order of `app:popupCharacters` works exactly? 
I see that for:
- `app:popupCharacters="9ó"` default is 9
- `app:popupCharacters="ó9"` default is ó
- `app:popupCharacters="őöøóôòõ9ō"` default is 9
- `app:popupCharacters="éè3êëēę"` default is 3

**Comment by tibbi** [comment]
well, it depends on the key. The best way is just testing it in the app itself.

**Comment by dmitriy-chernysh** [comment]
I've tested it and the digit is not selected by default for Polish 
https://youtube.com/shorts/nbrLrANGstQ

@starsep Please use the same ordering for characters as you can see in English layout. 

Screenshot from 2023-10-10 21-37-51

If there are 2 characters in ```app:popupCharacters```, the digit should be in a leading position, 
3 characters - the digit should be in the middle. 

In other cases - the digit should be shown above the key where you see a small digit inside.

**Comment by tibbi** [comment]
closing this as the fixed version has been accepted

**Pull request closed without merging**
