### PR TITLE
Direct boot aware fixes

### PR DESCRIPTION
**Pull request by Merkost**
Made some improvements.

Toolbar was being visible on a lock screen (not after reboot, just after the regular device lock) - **Fixed in first commit**

Toolbar visibility problem could be reproduced next way (**Fixed in second commit**):
1. Start typing something in a simple keyboard app field, for example
2. Lock the screen immediately
3. Unlock the device (should be with password) and you will see that toolbar is still invisible. You need to close keyboard and open again in order to update toolbar visibility.

### CODE REVIEW

**Comment by tibbi** [comment]
what should this fix? I still see the toolbar (clipboard etc) at every unlock on my Android 11

**Comment by Merkost** [comment]
> what should this fix? I still see the toolbar (clipboard etc) at every unlock on my Android 11

That' weird. You should have the next behaviour:

https://github.com/SimpleMobileTools/Simple-Keyboard/assets/56008710/481d92f3-731a-4c2b-a7e9-92ea3f0bc22c

**Comment by Merkost** [comment]
I have added additional check, could you please test again and provide a screenshot if you are still experiencing wrong behaviour. @tibbi

**Comment by tibbi** [comment]
ok thanks, should be good now

**Pull request merged**
