### PR TITLE
Feat/added secondary icon to key

### PR DESCRIPTION
**Pull request by ismailnurudeen**

### CODE REVIEW

**Comment by tibbi** [comment]
add some top and right margin to the globe please, also make the emojis smaller. Also make sure the globe uses the text color, it is now invisible in light theme

**Comment by ismailnurudeen** [comment]
Noted

**Comment by tibbi** [comment]
make the globe icon a bit bigger and move it more at the top corner

**Comment by tibbi** [comment]
maybe like this
icon

**Pull request merged**
