### PR TITLE
Adds xml for german keyboard layout

### PR DESCRIPTION
**Pull request by R1yuu**
Switched z and y to become qwertz. Switched top positions of a -> ä, o -> ö and u -> ü

### CODE REVIEW

**Comment by tibbi** [comment]
why have you removed some numbers from the popup characters?

**Comment by R1yuu** [comment]
Fixed the Popup Numbers.
Set the default for u and o to the numbers again, but left ö and ü next to the numbers for easy accessibility.

**Comment by tibbi** [comment]
this is just the xml layout, you still cannot select german keyboard in the app. How have you tested it?

**Comment by tibbi** [comment]
whatever, will add it myself. Thanks

**Pull request merged**
