### PR TITLE
Add a setting for showing key borders

### PR DESCRIPTION
**Pull request by Naveen3Singh**
Closes https://github.com/SimpleMobileTools/Simple-Keyboard/issues/39

### Changes:
- Add key borders
- Update keyboard view configuration on preference change
- Change emoji and space bar key width for proper alignment

### Screenshots:

<details>

<summary>Click to expand</summary>

 
 

</details>

### Notes:
- Background color is darkened when key borders are enabled.
- When using custom themes, the space bar also uses the same background as other keys for simplicity (the default grey color looks weird with custom background colors)

### CODE REVIEW

**Comment by tibbi** [comment]
lets make the borders visible in all themes including the light one, but do not show the borders at the popup keyboard that shows up at long pressing a key

**Comment by Naveen3Singh** [comment]
> lets make the borders visible in all themes including the light one

The borders are visible in light themes too (at least on my devices), are you referring to the 3rd screenshot?
(I just added it for reference, the borders are off there) 

> do not show the borders at the popup keyboard that shows up at long pressing a key

you got it

**Comment by Naveen3Singh** [comment]
> lets make the borders visible in all themes including the light one

nevermind, I can reproduce it when using a light theme while the system is in dark mode.

**Comment by Naveen3Singh** [comment]
found a UI glitch: whenever I launch an activity (as a result of some button action) while the keyboard is open, for a brief moment the keyboard moves to the top of the screen and only after that the activity is launched. I can reproduce this on master with any app (an easy way to reproduce this is opening the keyboard and tapping the keyboard setting button in the top-right corner)

**Comment by tibbi** [comment]
ye I know about it, it happens on Android 13 only, no? I tried a couple other keyboards too and they have the same. Only some dont. Thats why I call hideKeyboard() on many places at least within our apps to have the best UX.

**Comment by Naveen3Singh** [comment]
I can reproduce it on android 12 too but couldn't find any quick way to fix it. Doesn't seem to happen with https://github.com/openboard-team/openboard (basically an AOSP LatinIME fork) and https://github.com/florisboard/florisboard/
(Lmk if you want it to be fixed)

**Comment by tibbi** [comment]
no, that isnt a priority now. It wont be any simple fix.

**Comment by tibbi** [comment]
nice, seems to work just fine

**Pull request merged**
